type AccountGravatar = {
    readonly hash: string;
};
type AccountTmdb = {
    readonly avatar_path: string;
};
type AccountAvatar = {
    readonly gravatar: AccountGravatar;
    readonly tmdb: AccountTmdb;
};
export type AccountDetails = {
    readonly avatar: AccountAvatar;
    readonly id: number;
    readonly iso_639_1: string;
    readonly iso_3166_1: string;
    readonly name: string;
    readonly include_adult: boolean;
    readonly username: string;
};
export type AccountResult = {
    readonly success: boolean;
    readonly status_code: number;
    readonly status_message: string;
};
export type AccountFavoriteMovieItem = {
    readonly adult: boolean;
    readonly backdrop_path: string;
    readonly genre_ids: number[];
    readonly id: number;
    readonly original_language: string;
    readonly original_title: string;
    readonly overview: string;
    readonly popularity: number;
    readonly poster_path: string;
    readonly release_date: string;
    readonly title: string;
    readonly video: boolean;
    readonly vote_average: number;
    readonly vote_count: number;
};
export type AccountFavoriteTVShowItem = {
    readonly adult: boolean;
    readonly backdrop_path: string;
    readonly genre_ids: number[];
    readonly id: number;
    readonly original_country: string[];
    readonly original_name: string;
    readonly overview: string;
    readonly popularity: number;
    readonly poster_path: string;
    readonly first_air_date: string;
    readonly name: string;
    readonly vote_average: number;
    readonly vote_count: number;
};
export type AccountCustomListItem = {
    readonly description: string;
    readonly favorite_count: number;
    readonly id: number;
    readonly item_count: number;
    readonly iso_639_1: string;
    readonly list_type: string;
    readonly name: string;
    readonly poster_path: string;
};
export type AccountRatedMovieItem = {
    readonly adult: boolean;
    readonly backdrop_path: string;
    readonly genre_ids: number[];
    readonly id: number;
    readonly original_language: string;
    readonly original_title: string;
    readonly overview: string;
    readonly popularity: number;
    readonly poster_path: string;
    readonly release_date: string;
    readonly title: string;
    readonly video: boolean;
    readonly vote_average: number;
    readonly vote_count: number;
    readonly rating: number;
};
export type AccountRatedTVShowItem = {
    readonly adult: boolean;
    readonly backdrop_path: string;
    readonly genre_ids: number[];
    readonly id: number;
    readonly origin_country: string[];
    readonly original_language: string;
    readonly original_name: string;
    readonly overview: string;
    readonly popularity: number;
    readonly poster_path: string;
    readonly first_air_date: string;
    readonly name: string;
    readonly vote_average: number;
    readonly vote_count: number;
    readonly rating: number;
};
export type AccountRatedTVEpisodeItem = {
    readonly air_date: string;
    readonly episode_number: number;
    readonly id: number;
    readonly name: string;
    readonly overview: string;
    readonly production_code: string;
    readonly runtime: number;
    readonly season_number: number;
    readonly show_id: number;
    readonly still_path: string;
    readonly vote_average: number;
    readonly vote_count: number;
    readonly rating: number;
};
export type AccountWatchlistMovieItem = {
    readonly adult: boolean;
    readonly backdrop_path: string;
    readonly genre_ids: number[];
    readonly id: number;
    readonly original_language: string;
    readonly original_title: string;
    readonly overview: string;
    readonly popularity: number;
    readonly poster_path: string;
    readonly release_date: string;
    readonly title: string;
    readonly video: boolean;
    readonly vote_average: number;
    readonly vote_count: number;
};
export type AccountWatchlistTVShowItem = {
    readonly adult: boolean;
    readonly backdrop_path: string;
    readonly genre_ids: number[];
    readonly id: number;
    readonly origin_country: string[];
    readonly original_language: string;
    readonly original_name: string;
    readonly overview: string;
    readonly popularity: number;
    readonly poster_path: string;
    readonly first_air_date: string;
    readonly name: string;
    readonly vote_average: number;
    readonly vote_count: number;
};
