import { MediaType } from '../../shared';

export type AccountFavoriteMovieResultItem = Readonly<{
    adult: boolean;
    backdropPath: string;
    genreIds: Readonly<number[]>;
    id: number;
    originalLanguage: string;
    originalTitle: string;
    overview: string;
    popularity: number;
    posterPath: string;
    releaseDate: string;
    title: string;
    video: boolean;
    voteAverage: number;
    voteCount: number;
}>;

export type AccountFavoriteTvShowResultItem = Readonly<{
    adult: boolean;
    backdropPath: string;
    genreIds: Readonly<number[]>;
    id: number;
    originCountry: Readonly<string[]>;
    originalLanguage: string;
    originalName: string;
    overview: string;
    popularity: number;
    posterPath: string;
    firstAirDate: string;
    name: string;
    voteAverage: number;
    voteCount: number;
}>;
export type AccountCustomListResultItem = Readonly<{
    accountObjectId: string;
    adult: number;
    averageRating: number;
    createdAt: string;
    description: string;
    featured: number;
    id: number;
    iso3166_1: string;
    iso639_1: string;
    name: string;
    numberOfItems: number;
    public: number;
    revenue: string;
    runtime: number;
    sortBy: number;
    updatedAt: string;
}>;

export type AccountRatedMovieResultItem = Readonly<{
    adult: boolean;
    backdropPath: string;
    genreIds: Readonly<number[]>;
    id: number;
    originalLanguage: string;
    originalTitle: string;
    overview: string;
    popularity: number;
    posterPath: string;
    releaseDate: string;
    title: string;
    video: boolean;
    voteAverage: number;
    voteCount: number;
    accoutRating: number;
}>;
export type AccountRatedTvShowResultItem = Readonly<{
    adult: boolean;
    backdropPath: string;
    genreIds: Readonly<number[]>;
    id: number;
    originCountry: Readonly<string[]>;
    originalLanguage: string;
    originalName: string;
    overview: string;
    popularity: number;
    posterPath: string;
    firstAirDate: string;
    name: string;
    voteAverage: number;
    voteCount: number;
    accountRating: number;
}>;

export type AccountWatchlistMovieResultItem = Readonly<{
    adult: boolean;
    backdropPath: string;
    id: number;
    title: string;
    originalLanguage: string;
    originalTitle: string;
    overview: string;
    posterPath: string;
    mediaType: MediaType;
    genreIds: Readonly<number[]>;
    popularity: number;
    releaseDate: string;
    video: boolean;
    voteAverage: number;
    voteCount: number;
}>;
export type AccountWatchlistTvShowResultItem = Readonly<{
    adult: boolean;
    backdropPath: string;
    id: number;
    name: string;
    originalLanguage: string;
    originalName: string;
    overview: string;
    posterPath: string;
    mediaType: MediaType;
    genreIds: Readonly<number[]>;
    popularity: number;
    firstAirDate: string;
    voteAverage: number;
    voteCount: number;
    originCountry: Readonly<string[]>;
}>;
export type AccountRecommendedMovieItem = Readonly<{
    adult: boolean;
    backdropPath: string;
    id: number;
    title: string;
    originalLanguage: string;
    originalTitle: string;
    overview: string;
    posterPath: string;
    mediaType: MediaType;
    genreIds: Readonly<number[]>;
    popularity: number;
    releaseDate: string;
    video: boolean;
    voteAverage: number;
    voteCount: number;
}>;
export type AccountRecommendedTvShowItem = Readonly<{
    adult: boolean;
    backdropPath: string;
    id: number;
    name: string;
    originalLanguage: string;
    originalName: string;
    overview: string;
    posterPath: string;
    mediaType: MediaType;
    genreIds: Readonly<number[]>;
    popularity: number;
    firstAirDate: string;
    voteAverage: number;
    voteCount: number;
    originCountry: string;
}>;
